const NAME_SPACE = 'COURSE';

export const COURSE_ACTION = {
    GET_COURSE_START: `${NAME_SPACE}/GET_COURSE_START`,
    GET_COURSE_SUCCESS: `${NAME_SPACE}/GET_COURSE_SUCCESS`, 
    GET_COURSE_FAILURE: `${NAME_SPACE}/GET_COURSE_FAILURE`,
    UPDATE_COURSE_START: `${NAME_SPACE}/UPDATE_COURSE_START`,
    UPDATE_COURSE_SUCCESS: `${NAME_SPACE}/UPDATE_COURSE_SUCCESS`,
    UPDATE_COURSE_FAILURE: `${NAME_SPACE}/UPDATE_COURSE_FAILURE`
}

export const getCourseActionCreator = () => ({
    type: COURSE_ACTION.GET_COURSE_START
})

export const updateCourseActionCreator = payload => ({
    type: COURSE_ACTION.UPDATE_COURSE_START,
    payload
})
